---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/60d6704195e3b8001676a2cb/webhook/forestry
sections:
- type: document
  path: _data/config.json
  label: Site Configuration
  templates:
  - config
- type: document
  path: blog/index.md
  label: Blog
  templates:
  - blog
- type: document
  path: portfolio/index.md
  label: Portfolio
  templates:
  - portfolio
- type: jekyll-pages
  label: Pages
  create: all
  new_doc_ext: md
  templates:
  - advanced
  - page
  - post
  - project
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
